config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'prototypes#index'
  resources :prototypes do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :edit, :update, :destroy]
  end
  resources :users, only: [:show, :edit, :update]
  resources :tags, only: [:index, :show, :destroy]
end

app/models/captured_image.rb
class CapturedImage < ActiveRecord::Base
  belongs_to :Prototype

  mount_uploader :content, PrototypeImageUploader

  enum status: %i(main sub)

  validates :content,
            :status,
            presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :prototype
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :prototype, counter_cache: :likes_count
end

app/models/prototype.rb
class Prototype < ActiveRecord::Base
  belongs_to :user
  has_many :prototype_tags, dependent: :destroy
  has_many :captured_images, dependent: :destroy
  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :tags, through: :prototype_tags

  accepts_nested_attributes_for :captured_images, reject_if: :reject_sub_images

  accepts_nested_attributes_for :tags, reject_if: :reject_sub_tags

  validates :title,
            :catch_copy,
            :concept,
            presence: true

  def reject_sub_images(attributed)
    attributed['content'].blank?
  end

  def reject_sub_tags(attributed)
    attributed['name'].blank?
  end

  def set_main_thumbnail
    captured_images.main.first.content
  end

  def posted_date
    created_at.strftime('%b %d %a')
  end

  def like_user(user_id)
   likes.find_by(user_id: user_id)
  end
  
  def save_tags(tags)
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    old_tags = current_tags - tags
    new_tags = tags - current_tags

    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(name:old_name)
    end

    new_tags.each do |new_name|
      prototype_tag = Tag.find_or_create_by(name:new_name)
      self.tags << prototype_tag
    end

  end
end

app/models/prototype_tag.rb
class PrototypeTag < ActiveRecord::Base
  belongs_to :prototype
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :prototype_tags, dependent: :destroy
  has_many :prototypes, through: :prototype_tags

  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, UserImageUploader

  has_many :prototypes
  has_many :comments

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:name, :profile, :position, :occupation, :avatar])

    devise_parameter_sanitizer.permit(:account_update, keys:[:name, :profile, :position, :occupation, :avatar])
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :edit, :destroy]

  def create
    @comment=Comment.create(comment_params)
    respond_to do |format|
      format.html {redirect_to prototype_path(id:params[:prototype_id])}
      format.json
    end
  end

  def edit
    @prototype = Prototype.find(params[:prototype_id])
    @comment = Comment.find(params[:id])
  end

  def update
    comment = Comment.find(params[:id])
    comment.update(comment_params)
    redirect_to prototype_path(id: params[:prototype_id])
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.delete
    redirect_to prototype_path(id: params[:prototype_id])
  end

  private
    def comment_params
      params.require(:comment).permit(:body).merge(prototype_id:params[:prototype_id],user_id: current_user.id)
    end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @like = Like.create(user_id: current_user.id, prototype_id: params[:prototype_id])
    @likes = Like.where(prototype_id: params[:prototype_id])
    @prototype = Prototype.find(params[:prototype_id])
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, prototype_id: params[:prototype_id])
    like.destroy
    @likes = Like.where(prototype_id: params[:prototype_id])
    @prototype = Prototype.find(params[:prototype_id])
  end

end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_prototype, only: [:show, :edit, :update]

  def index
    @prototypes = Prototype.order("created_at DESC").page(params[:page]).per(8)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def new
    @prototype = Prototype.new
    @prototype.captured_images.build
    @prototype.tags.build
  end

  def edit
    @captured_images_main = @prototype.captured_images.where("status='0'")
    @captured_images_sub = @prototype.captured_images.where("status='1'")
    @captured_images_new = @prototype.captured_images.build
    # 入力用のフォーム作成のため、buildメソッド使用
    @tags_new = @prototype.tags.build
    # 同上
    @tags_existing = @prototype.tags.where.not(id: nil)
    # tags_new を省くためにwhere.notを使用
  end

  def update
    tags = params[:prototype][:tags].reject(&:empty?)
    if @prototype.user_id == current_user.id
      @prototype.update(prototype_update_params)
      @prototype.save_tags(tags)
      redirect_to :root, notice: 'Prototype was successfully updated'
      return
    else
      render action: :edit
      return
    end
  end

  def create
    tags = params[:prototype][:tags].reject(&:empty?)
    @prototype = Prototype.new(prototype_create_params)
    if @prototype.save
      @prototype.save_tags(tags)
      redirect_to :root, notice: 'New prototype was successfully created'
    else
      redirect_to ({ action: "new" }), alert: 'New prototype was unsuccessfully created'
     end
  end

  def show
    @comment = Comment.new
    @comments = @prototype.comments.all
  end

  def destroy
    prototype = Prototype.find(params[:id])
    if prototype.user_id == current_user.id
      prototype.destroy
      redirect_to :root, notice: 'Prototype was successfully deleted'
    else
      render action: :edit
    end
  end

  private

  def set_prototype
    @prototype = Prototype.find(params[:id])
  end

  def prototype_create_params
    params.require(:prototype).permit(
      :title,
      :catch_copy,
      :concept,
      :user_id,
      captured_images_attributes: [:content, :status]
    )
  end

  def prototype_update_params
    params.require(:prototype).permit(
      :title,
      :catch_copy,
      :concept,
      :user_id,
      captured_images_attributes: [:content, :status, :id]
    )
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
  end

  def destroy
    @tag = Tag.find(params[:id])
    @prototype = Prototype.find(params[:prototype_id])
    @prototype_tag = PrototypeTag.find_by(tag_id: params[:id], prototype_id: params[:prototype_id])
    if user_signed_in? && current_user.id == @prototype.user.id
      @prototype_tag.destroy
      redirect_to prototype_path(@prototype), notice: 'Tag was successfully deleted'
    else
       redirect_to prototype_path(@prototype), alert: 'Tag was unsuccessfully deleted'
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def show
    @prototypes = @user.prototypes
  end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to :root, notice: 'Your user infomation was successfully updated'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :position,
      :profile,
      :occupation,
      :avatar
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/edit.html.haml
.container.proto-page
  %header.row.user-nav
    .col-md-6
      .media
        .media-left
          = link_to user_path(@prototype.user) do
            = image_tag(@prototype.user.avatar.thumb, alt: "profile_photo", class: "media-object", style: "width: 64px; height: 64px;")
        .media-body
          %h4#top-aligned-media.media-heading
            = @prototype.title
          .proto-user
            by
            = link_to "#{@prototype.user.name}", user_path(@prototype.user)
            .degree
              = @prototype.user.position
  .row
    .col-md-9.image-box
      = image_tag(@prototype.set_main_thumbnail.large, class: 'img-responsive img-size-fix', style: "margin: 0 auto;")
    .col-md-3
      %ul.proto-sub-list.list-group
        - @prototype.captured_images.sub.each do |image|
          %li.list-group-item
            = image_tag(image.content, class: 'img-responsive')
  .row.proto-description
    .col-md-3
      %h4 Catch Copy
      %p
        = @prototype.catch_copy
    .col-md-6
      %h4 Concept
      %p
        = @prototype.concept
    .col-md-3
      %h4 Tag List
      %ul.proto-tag-list.list-inline
        %li
          %a{href: "#", class: "btn btn-default"} iPad
        %li
          %a{href: "#", class: "btn btn-default"} wireframe


  .comments-form
  %h4 Edit a comment
  = form_for ([@prototype,@comment]) do |f|
    = f.text_field :body, placeholder: "Sign in to put your comment"

    = f.submit "EDIT"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=US-ASCII", "http-equiv" =>  "Content-Type"}/
    %title Protospace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' =>  true
    = javascript_include_tag 'application', 'data-turbolinks-track' =>  true
    = csrf_meta_tags
    %link{:crossorigin => "anonymous", :href => "https://use.fontawesome.com/releases/v5.0.13/css/all.css", :integrity => "sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp", :rel => "stylesheet"}


  %body
    = render "shared/header"
    = render "shared/messages"
    = yield
    = render "shared/footer"

app/views/likes/_like.html.haml
- if user_signed_in?
  - if prototype.like_user(current_user.id)
    = button_to prototype_like_path("likes", prototype_id: prototype.id), method: :delete, id: "like-button", remote: true do
      = image_tag("icon_red_heart.png")
      %span
        = prototype.likes_count
  - else
    = button_to prototype_likes_path(prototype), id: "like-button", remote: true do
      = image_tag("icon_grey_heart.png")
      %span
        = prototype.likes_count
- else
  = image_tag("icon_grey_heart.png")
  %span
    = prototype.likes_count

app/views/likes/create.js.erb
$("#like-zone").html("<%= j(render partial: 'like', locals: { prototype: @prototype, likes: @likes, like: @like}) %>");

app/views/likes/destroy.js.erb
$("#like-zone").html("<%= j(render partial: 'like', locals: { prototype: @prototype, likes: @likes }) %>");

app/views/prototypes/_prototype.html.haml
.col-sm-4.col-md-3.proto-content
  .thumbnail
    = link_to image_tag(prototype.set_main_thumbnail), prototype_path(prototype)
    .caption
      %h3
        = prototype.title
      .proto-meta
        .proto-user
          = link_to prototype.user.name, user_path(prototype.user)
        .proto-posted
          = prototype.posted_date
      %ul.proto-tag-list.list-inline
        -prototype.tags.each do |tag|
          %li
            %a.btn.btn-default{ href:"/tags/#{tag.id}"}#{tag.name}
      .proto-likes
        -if prototype.likes.present?
          %p #{prototype.likes_count} likes
        -else
          %p 0 likes

app/views/prototypes/edit.html.haml
.container.proto-new
  = form_for @prototype do |f|
    = f.hidden_field :user_id, value: current_user.id
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h4 Title
          .proto-new-title
            = f.text_field :title, required: true, autofocus: true
      .row
        .col-md-12
          %h4 Main Thumbnail
          .cover-image-upload#main_image_uploader
            = f.fields_for :captured_images, @captured_images_main do |image|
              = image_tag(@prototype.set_main_thumbnail.large, alt: "main_photo", class: 'img-responsive img-size-fix', style: "margin: 0 auto;")
              = image.file_field :content
              = image.hidden_field :status, value: "main"
        .col-md-12
          %h4 Sub Thumbnails
          %ul.proto-sub-list.list-group
            -@captured_images_sub.each do |sub_image|
              %li.list-group-item.col-md-4
                .image-upload
                  = f.fields_for :captured_images, sub_image do |image|
                    = image_tag(sub_image.content, alt: "main_photo", class: 'img-responsive img-size-fix',style: "margin: 0 auto;,height: 200px;")
                    = image.file_field :content
                    = image.hidden_field :status, value: "sub"
            - (3 - @captured_images_sub.length).times do |i|
              %li.list-group-item.col-md-4
                .image-upload
                  = f.fields_for :captured_images, @captured_images_new do |image|
                    %img
                    = image.file_field :content
                    = image.hidden_field :status, value: "sub"
      .row.proto-description
        .col-md-12
          %h4 Catch Copy
          = f.text_field :catch_copy, require: true
        .col-md-12
          %h4 Concept
          = f.text_area :concept, require: true
        .col-md-12
          %h4 Tag List
          .row
            - 3.times do |i|
              .col-md-3
                -if i == 0
                  = f.text_field :tags, name:"prototype[tags][]", require: true, placeholder: "ex)Web", value:""
                -else
                  = f.text_field :tags, name:"prototype[tags][]", placeholder: "ex)Web", value:""
      .row.text-center.proto-btn
        = f.submit "UPDATE", id: "button", class: "btn btn-lg btn-primary btn-block"
        = link_to 'DELETE', "/prototypes/#{@prototype.id}", method: :DELETE, class: "btn btn-lg btn-primary btn-block"

app/views/prototypes/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.btn-default
          = link_to "Popular", "#", id: "btn-popular"
        %li.btn-default
          = link_to "Newest", "#", id: "btn-newest"
      = link_to "VIEW TAGS", "/tags", class: "btn btn-default col-lg-1"

.container.proto-list
  .row.proto-zone
    = render partial: 'prototype', collection: @prototypes
.text-center
  = paginate(@prototypes)

app/views/prototypes/new.html.haml
.container.proto-new
  = form_for @prototype do |f|
    = f.hidden_field :user_id, value: current_user.id
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h4 Title
          .proto-new-title
            = f.text_field :title, required: true, autofocus: true, placeholder: "Input Title"
      .row
        .col-md-12
          %h4 Main Thumbnail
          .cover-image-upload#main_image_uploader
            = f.fields_for :captured_images do |image|
              %img
              = image.file_field :content, required: true
              = image.hidden_field :status, value: "main"
        .col-md-12
          %h4 Sub Thumbnails
          %ul.proto-sub-list.list-group
            - 3.times do |i|
              %li.list-group-item.col-md-4
                .image-upload
                  = f.fields_for :captured_images do |image|
                    %img
                    = image.file_field :content
                    = image.hidden_field :status, value: "sub"
      .row.proto-description
        .col-md-12
          %h4 Catch Copy
          = f.text_field :catch_copy, require: true, placeholder: "Input Catch Copy"
        .col-md-12
          %h4 Concept
          = f.text_area :concept, require: true, placeholder: "Input Concept"
        .col-md-12
          %h4 Tag List
          .row
            - 3.times do |i|
              .col-md-3
                -if i == 0
                  = f.text_field :tags, name:"prototype[tags][]", require: true, placeholder: "ex)Web", value:""
                -else
                  = f.text_field :tags, name:"prototype[tags][]", placeholder: "ex)Web", value:""
      .row.text-center.proto-btn
        = f.submit "PUBLISH", id: "button", class: "btn btn-lg btn-primary btn-block"

app/views/prototypes/show.html.haml
.container.proto-page
  %header.row.user-nav
    .col-md-6
      .media
        .media-left
          = link_to user_path(@prototype.user) do
            = image_tag(@prototype.user.avatar.thumb, alt: "profile_photo", class: "media-object", style: "width: 64px; height: 64px;")
        .media-body
          %h4#top-aligned-media.media-heading
            = @prototype.title
          .proto-user
            by
            = link_to "#{@prototype.user.name}", user_path(@prototype.user)
            .degree
              = @prototype.user.position
    .col-md-6.text-right
      .likes#like-zone
        = render partial: 'likes/like', locals: { prototype: @prototype, likes: @likes }
      -if user_signed_in? && current_user.id == @prototype.user.id
        .btn.btn-default.btn-edit.btn-margin-top
          = link_to "edit", edit_prototype_path(@prototype)
  .row
    .col-md-9.image-box
      = image_tag(@prototype.set_main_thumbnail.large, class: 'img-responsive img-size-fix', style: "margin: 0 auto;")
    .col-md-3
      %ul.proto-sub-list.list-group
        - @prototype.captured_images.sub.each do |image|
          %li.list-group-item
            = image_tag(image.content, class: 'img-responsive')
  .row.proto-description
    .col-md-3
      %h4 Catch Copy
      %p
        = @prototype.catch_copy
    .col-md-6
      %h4 Concept
      %p
        = @prototype.concept
    .col-md-3
      %h4 Tag List
      %ul.proto-tag-list.list-inline
        -@prototype.tags.each do |tag|
          %li
            %a{href: "/tags/#{tag.id}", class: "btn btn-default"} #{tag.name}
            -if user_signed_in? && current_user.id == @prototype.user.id
              =link_to "×", tag_path(id:tag.id, prototype_id: @prototype.id), data:{confirm:"「#{tag.name}」タグを削除します。よろしいですか?"}, method: :delete
  .col-md-3#comment-zone
    .comments-list.clearfix
      %h4.comments Comments
      - @comments.each do |comment|
        .comments-contents
          %h5.comments-list__username
            = comment.user.name
          %p.comments-list__body
            = comment.body
          .comments-list__edit
            = link_to "EDIT", edit_prototype_comment_path(@prototype,comment)
          .comments-list__destroy
            = link_to "DESTROY", "/prototypes/#{@prototype.id}/comments/#{comment.id}", method: :delete
    .comments-form
    %h4 Write a comment
    = form_for ([@prototype,@comment]) do |f|
      = f.text_field :body, placeholder: "Sign in to put your comment", class:"form-control"
      = f.submit "COMMENT",class:"btn btn-default btn-margin-top"

app/views/shared/_footer.html.haml
.container
  %footer
    %p &copy; PROTO SPACE 2015.

app/views/shared/_header.html.haml
.navbar.navbar-default.navbar-static-top.navbar-fixed-top
  .container
    %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    .navbar-brand
      = link_to image_tag("logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "36px"), root_path
    .navbar-collapse.collapse.navbar-responsive-collapse
      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            = link_to "#", id:'dropdown-toggle', class: 'dropdown-toggle', role: 'button', 'aria-expanded' =>  'false', 'data-toggle' => 'dropdown' do
              #{current_user.name}
              %span.caret
            %ul.dropdown-menu{role: "menu"}
              %li
                = link_to 'Edit', edit_user_path(current_user)
              %li
                = link_to 'My Page', user_path(current_user)
              %li
                = link_to 'Logout', destroy_user_session_path, method: :delete
          %li
            .btn.btn-default
              = link_to "New Photo", new_prototype_path, style: "color: #337ab7;"
      - else
        %ul.nav.navbar-nav.navbar-right
          %li
            .btn.btn-primary.navbar-btn
              = link_to 'Get Started', new_user_session_path

app/views/shared/_messages.html.haml
- flash.each do |key, value|
  - if value == notice
    = content_tag(:div, value, class: "alert alert--success")
  - if value == alert
    = content_tag(:div, value, class: "alert alert--danger")

app/views/tags/_tag.html.haml
.col-sm-4.col-md-3.proto-content
  .thumbnail
    %a{href: "/tags/#{tag.id}"}
      %button.btn.btn-tag.tag-name{name: "button", type: "submit"}
        = tag.name
    .tag-meta
      %a.label.label-default.tag-list-number.tag-project{href: "/tags/#{tag.id}"} #{tag.prototypes.size} Projects

app/views/tags/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.btn-default.btn-popular
          = link_to "Popular", "#"
        %li.btn-default.btn-popular
          = link_to "Newest", "#"
      = link_to "VIEW TAGS", "#", class: "btn btn-default col-lg-1"

.container.proto-list
  .row
    = render partial: 'tags/tag', collection: @tags

app/views/tags/show.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.btn-default.btn-popular
          = link_to "Popular", "#"
        %li.btn-default.btn-popular
          = link_to "Newest", "#"
      = link_to "VIEW TAGS", "#", class: "btn btn-default col-lg-1"

.container
  .row
    .col-sm-12.proto-content
      .thumbnail
        %button.btn.btn-tag.tag-name{name: "button", type: "submit"}#{@tag.name}
        .tag-meta
          %a.label.label-default.tag-list-number.tag-project{ href: "/tags/#{@tag.id}"} #{@tag.prototypes.size} Projects

.container.proto-list
  .row
    = render partial: 'prototypes/prototype', collection: @tag.prototypes

app/views/users/edit.html.haml
.container.user-new.clearfix
  = form_for @user do |f|
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h2 Edit
          .user-name_image.row
            .user-name.col-md-10
              = f.text_field :name, placeholder: "Input Username", autofocus: true, required: true
            .user-image.col-md-2
              %img{ style: "" }
              = f.file_field :avatar
          .user-email
            = f.text_field :email, placeholder: "Input Email", required: true
        .col-md-12
          %h4 Position
          .user-user-member.row
            .user-name.col-md-12
              = f.text_field :position, placeholder: "Input Position"
          %h4 Profile
          .user-user-profile.row
            .user-name.col-md-12
              = f.text_area :profile, placeholder: "Input Profile", size:"30×4"
          %h4 Occupation
          .user-name_image.row
            .user-name.col-md-12
              = f.text_area :occupation, placeholder: "Input Occupation", size: "30×4"
        .row.text-center.user-btn
          .actions
            = f.submit "SAVE", id: "button", class: "btn btn-lg btn-primary btn-block"

app/views/users/show.html.haml
.container.user-page
  %header.user-nav
    .media
      .media-left
        = image_tag(@user.avatar.thumb, alt: "profile_photo", class: "media-object", style: "width: 64px; height: 64px;")
      .media-body
        %h4#top-aligned-media.media-heading
          = @user.name
          %span.label.label-default.project-number
            #{@user.prototypes.size}
            %i Projects
        .proto-user
          %span.degree= @user.position
        .row
          .col-md-6
            %h4 Profile
            %p= @user.profile
          .col-md-6
            %h4 Occupation
            %p= @user.occupation
.container.proto-list
  .row
    = render partial: 'prototypes/prototype', collection: @prototypes